### ISSUE TITLE
running speed

### ISSUE THREAD

**Issue by zhangy76** [muelea/selfcontact#7]
Hi,

Thanks for proposing this meaningful work! I wonder if the running speed can be improved so that the proposed loss functions, i.e. inside, outside, normal losses, can be incorporated into a training framework?

Thanks,

**Comment by muelea** [comment]
Yes, the inside / outside segmentation is quite slow, and winding numbers are much faster than ray tracing. However, there are faster implementations you can try. Otherwise you can test less points by downsampling (not all vertices) or use multiple GPUs.

Here is the winding number's references: https://dl.acm.org/doi/pdf/10.1145/2461912.2461916

**Comment by zhangy76** [comment]
Thank you very much for the reply! I will try these ideas.

Also, I wonder what software did you use to divide the mesh into segments with known boundary vertices and segment IDs?
